services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      # Admin credentials for Keycloak console
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      # Database configuration (using H2 for development)
      KC_DB: dev-file
      
      # HTTP settings
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      
      # Logging
      KC_LOG_LEVEL: INFO
    
    command:
      - start-dev
      - --import-realm
    
    ports:
      # Keycloak web interface and API
      - "8080:8080"
    
    volumes:
      # Persist Keycloak data
      - keycloak_data:/opt/keycloak/data
      # Import realm configuration with pre-configured client
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    networks:
      - keycloak-network

volumes:
  keycloak_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge
